// BlueprintGeneratedClass BPFL_VO_Combat.BPFL_VO_Combat_C
// Size: 0x28 (Inherited: 0x28)
struct UBPFL_VO_Combat_C : UBlueprintFunctionLibrary {

	void VO Combat Downed Something(struct AS_CharacterBase* Speaker, struct AS_CharacterBase* DownedThing, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VO Combat Downed Something // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Combat_EnemyTeamEliminated(struct AS_CharacterBase* Speaker, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VO_Combat_EnemyTeamEliminated // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Combat_BossKilled(struct AS_CharacterBase* Speaker, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VO_Combat_BossKilled // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Ability_NotReady(struct AS_CharacterBase* Speaker, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VO_Ability_NotReady // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Status_ColdResponse(struct AS_CharacterBase* Speaker, float OldValue, float NewValue, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VO_Status_ColdResponse // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Status_HungerResponse(struct AS_CharacterBase* Speaker, float OldValue, float NewValue, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VO_Status_HungerResponse // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Combat_Reloading(struct AS_CharacterBase* Speaker, struct FS_DialogueContext WeaponContext, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VO_Combat_Reloading // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Combat_KilledSomething(struct AS_CharacterBase* Speaker, struct AS_CharacterBase* KilledThing, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VO_Combat_KilledSomething // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Combat_DamageResponse(struct AS_CharacterBase* Speaker, enum class ES_StatChangeCauseType Cause, float OldHealth, float NewHealth, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VO_Combat_DamageResponse // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Combat_GrenadeThrown(struct AS_CharacterBase* Speaker, struct FS_DialogueContext Grenade Context, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VO_Combat_GrenadeThrown // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Combat_GrenadeNearby(struct AS_CharacterBase* Speaker, struct ABP_PROJ_Grenade_Base_C* Grenade Projectile, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VO_Combat_GrenadeNearby // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Combat_CharacterDown(struct AS_CharacterBase* Speaker, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VO_Combat_CharacterDown // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Ability_Activated(struct AS_CharacterBase* Speaker, struct UGameplayAbility* Ability, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VO_Ability_Activated // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VOHelper_ GetAttitudeContextValue(struct AS_CharacterBase* A, struct AS_CharacterBase* B, struct UObject* __WorldContext, struct FS_DialogueContextValue Attitude); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VOHelper_ GetAttitudeContextValue // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xffff8008e4a10000
	bool VOHelper_StatCrossedThreshold(float Threshold, float OldHealth, float NewHealth, struct UObject* __WorldContext); // Function BPFL_VO_Combat.BPFL_VO_Combat_C.VOHelper_StatCrossedThreshold // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xffff8008e4a10000
};

