// BlueprintGeneratedClass BPFL_VO_Interaction.BPFL_VO_Interaction_C
// Size: 0x28 (Inherited: 0x28)
struct UBPFL_VO_Interaction_C : UBlueprintFunctionLibrary {

	void VOHelper_GetInteractableContext_Complete(struct AS_CharacterBase* Speaker, struct AS_InteractableActor* InteractableActor, struct UObject* __WorldContext, struct FS_DialogueContext Context); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VOHelper_GetInteractableContext_Complete // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xffff8008e4a10000
	void VO_Interaction_HealUp(struct AS_CharacterBase* Speaker, struct UObject* __WorldContext); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VO_Interaction_HealUp // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Interaction_EatFood(struct AS_CharacterBase* Speaker, struct UObject* __WorldContext); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VO_Interaction_EatFood // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Ping_PingResponse(struct AS_PlayerController* pingingPlayerController, struct AS_CharacterBase* Speaker, enum class ES_PingInfoType PingType, struct AActor* PingedActor, struct UObject* __WorldContext); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VO_Ping_PingResponse // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Interaction_WarmingUp(struct AS_CharacterBase* Speaker, struct UObject* __WorldContext); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VO_Interaction_WarmingUp // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Interaction_Searchable(struct AS_CharacterBase* Speaker, struct AS_InteractableActor* Interactable, struct UObject* __WorldContext); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VO_Interaction_Searchable // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Interaction_KeeperInteractable_Completed(struct AS_CharacterBase* Speaker, struct ABP_KeeperInteractable_C* KeeperInteractable, int32_t InteractingTeam, struct UObject* __WorldContext); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VO_Interaction_KeeperInteractable_Completed // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Interaction_KeeperInteractable_Disengage(struct AS_CharacterBase* Speaker, struct ABP_KeeperInteractable_C* KeeperInteractable, int32_t InteractingTeam, struct UObject* __WorldContext); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VO_Interaction_KeeperInteractable_Disengage // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Interaction_KeeperInteractable_Harassed(struct AS_CharacterBase* Speaker, struct ABP_KeeperInteractable_C* KeeperInteractable, int32_t InteractingTeam, struct UObject* __WorldContext); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VO_Interaction_KeeperInteractable_Harassed // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Interaction_KeeperInteractable_Begin(struct AS_CharacterBase* Speaker, struct ABP_KeeperInteractable_C* KeeperInteractable, int32_t InteractingTeam, struct UObject* __WorldContext); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VO_Interaction_KeeperInteractable_Begin // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Interaction_Revive_Complete(struct AS_CharacterBase* Speaker, struct AS_CharacterBase* ReviveTarget, struct UObject* __WorldContext); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VO_Interaction_Revive_Complete // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Interaction_Revive_Begin(struct AS_CharacterBase* Speaker, struct AS_CharacterBase* ReviveTarget, struct UObject* __WorldContext); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VO_Interaction_Revive_Begin // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VO_Interaction_EnterSeat(struct AS_CharacterBase* Speaker, struct USC_Seat* Seat, struct UObject* __WorldContext); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VO_Interaction_EnterSeat // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void VOHelper_GetSeatContext(struct AS_CharacterBase* Character, struct USC_Seat* Seat, struct UObject* __WorldContext, struct FS_DialogueContext Context); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VOHelper_GetSeatContext // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xffff8008e4a10000
	void VOHelper_GetPlayerContext(struct AS_CharacterBase* Speaker, struct AS_CharacterBase* TargetContext, struct UObject* __WorldContext, struct FS_DialogueContext Context); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VOHelper_GetPlayerContext // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xffff8008e4a10000
	void VOHelper_GetInteractableContext(struct AS_CharacterBase* Speaker, struct AS_InteractableActor* InteractableActor, struct UObject* __WorldContext, struct FS_DialogueContext Context); // Function BPFL_VO_Interaction.BPFL_VO_Interaction_C.VOHelper_GetInteractableContext // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0xffff8008e4a10000
};

