// BlueprintGeneratedClass BPI_GameModeTeams.BPI_GameModeTeams_C
// Size: 0x28 (Inherited: 0x28)
struct UBPI_GameModeTeams_C : UInterface {

	void RefreshHVO_BPI(); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.RefreshHVO_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Denoob_BPI(struct AS_PlayerController* NotNoob); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Denoob_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void NoobBlessingCheck_BPI(struct AS_PlayerController* Player, bool ConferBlessing); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.NoobBlessingCheck_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void IsTeamEliminated_BPI(int32_t TeamIndex, bool Eliminated); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.IsTeamEliminated_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void IsTransformWithinStormCircleX(struct FTransform Transform, float RadiusScalar, int32_t CategoryX, bool IsInCircle); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.IsTransformWithinStormCircleX // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void CheckFor1up_BPI(int32_t TeamIndex); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.CheckFor1up_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetExpectedPlayers_BPI(int32_t ExpectedNumber); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetExpectedPlayers_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetResurrectionTokenDef_BPI(struct US_ItemData* NewParam); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetResurrectionTokenDef_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void CloneBackupEnabled_BPI(bool CloneBackupEnabled); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.CloneBackupEnabled_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterScourgeLocker(struct AActor* ScourgeLocker); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterScourgeLocker // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void TeamRASPed_BPI(int32_t TeamIndex); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.TeamRASPed_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void RASPEnabled_BPI(bool RASPs Available); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.RASPEnabled_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Mutator:DeathEater_BPI(bool DeathEaterActive); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Mutator:DeathEater_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Mutator:Dropsquad_BPI(bool Dropsquad Active); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Mutator:Dropsquad_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void SupplyDropCompleteMatchwide_BPI(struct APlayerController* completingPlayer); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.SupplyDropCompleteMatchwide_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void SpaceJunkCompleteMatchwide_BPI(struct APlayerController* completingPlayer); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.SpaceJunkCompleteMatchwide_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:Decommission Superspawner(struct AActor* Actor); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:Decommission Superspawner // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void OnResurrect_BPI(struct APlayerController* PlayerControllerToRez, struct FTransform SpawnTransform, struct APlayerController* PlayerControllerThatUsedRezToken); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.OnResurrect_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Itemrez_BPI(int32_t TeamIndex, struct TArray<struct FTransform> SpawnPoints, struct AS_PlayerController* RezActivator); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Itemrez_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void CloneKitEnabled_BPI(bool CloneKit); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.CloneKitEnabled_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterSuperspawner(struct AActor* Actor, bool Exclude Supply Pods, bool Exclude Data Uplinks, bool Exclude RASP, bool Exclude Space Junk, bool Exclude Scourge Locker); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterSuperspawner // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RemoveBossFromArrays(struct AActor* BossActor); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RemoveBossFromArrays // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterDropshipCamera(struct AActor* Actor); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterDropshipCamera // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void BayDoorActivated_BPI(int32_t BayNumber); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.BayDoorActivated_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void HatchActivated_BPI(int32_t HatchNumber); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.HatchActivated_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetBossDataValue_BPI(bool MidagameBoss,NotEndgameBoss, bool EarlygameBoss,NotTheOthers, int32_t Datapoint Value); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetBossDataValue_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void TopTeamsByScore_BPI(int32_t NumTeams, struct TArray<int32_t> TeamIndexes); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.TopTeamsByScore_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Check:EliminatedOnWipe_BPI(bool TeamEliminatedWhenWiped); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Check:EliminatedOnWipe_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Module:SpecialCaseTuningData_BPI(bool Use Special Case Data); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Module:SpecialCaseTuningData_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Mutator:SuddenDeath_BPI(bool SuddenDeathActive); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Mutator:SuddenDeath_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Mutator:Vanguard_BPI(bool VanguardActive); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Mutator:Vanguard_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Mutator:Thunderdome_BPI(bool ThunderdomeActive); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Mutator:Thunderdome_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Mutator:SpecialEvent_BPI(bool SpecialEventActive); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Mutator:SpecialEvent_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Mutator:Safari_BPI(bool SafariActive); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Mutator:Safari_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Mutator:Headhunter_BPI(bool HeadhunterActive); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Mutator:Headhunter_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Mutator:GunFu_BPI(bool GunFu Active); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Mutator:GunFu_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Mutator:Arsenal_BPI(bool ArsenalActive); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Mutator:Arsenal_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void OnDropshipLanded(struct AActor* Dropship, struct AActor* Camera); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.OnDropshipLanded // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void IsLocationInStorm_BPI(struct FVector Location, bool In Any Storm); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.IsLocationInStorm_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void ReadyDropshipDoors(struct TArray<struct FTransform> hatches, struct TArray<struct FTransform> bays); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.ReadyDropshipDoors // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void ChooseAndDeployRASP_BPI(struct FVector flareLoc); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.ChooseAndDeployRASP_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AdjustNumberOfHighValueObjectives_BPI(int32_t -1); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.AdjustNumberOfHighValueObjectives_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:BasicObjectiveCloaked(); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:BasicObjectiveCloaked // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void ReportPlayspaceAnchor_BPI(struct FVector Anchor); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.ReportPlayspaceAnchor_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetPlayerStartLocations_BPI(struct TArray<struct FVector> PlayerStartLocs, bool PlayerStartsDetermined); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetPlayerStartLocations_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetNumberOfPlayersOnTeam_BPI(int32_t TeamIndex, int32_t PlayerCount); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetNumberOfPlayersOnTeam_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:Get BossBannerData(enum class EBossEncounter BossType, struct FName BannerTitle, struct FName BannerSubtitle, enum class ES_LocationType LocType, enum class ES_LocationDifficultyTier LocDifficulty, enum class ES_LocationFaction LocFaction); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:Get BossBannerData // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterMidgameBoss(struct AActor* MidgameBoss); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterMidgameBoss // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetYoShit(); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetYoShit // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetCircleCollapseTimerTest_BPI(float CircleCollapseInterval); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetCircleCollapseTimerTest_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void SetCircleCollapseTimerTest_BPI(float Seconds); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.SetCircleCollapseTimerTest_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void ObjectiveComplete_BPI(int32_t CompletingTeam, int32_t NumObjectives); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.ObjectiveComplete_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void SingleTeamHurryupActivated(bool HurryupActive); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.SingleTeamHurryupActivated // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterWeaponChest(struct AActor* ChestSpawner); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterWeaponChest // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetDropshipDefinition_BPI(struct AActor* DropshipClassRef); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetDropshipDefinition_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterEventProp(struct AActor* prop); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterEventProp // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void BossEngaged_BPI(struct AS_PlayerController* Player, struct AActor* Boss); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.BossEngaged_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void PlayerAboardDropship_BPI(struct AS_PlayerCharacter* Player); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.PlayerAboardDropship_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceHVOComplete_BPI(int32_t Team); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.AnnounceHVOComplete_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceHVOStarted_BPI(); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.AnnounceHVOStarted_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void WantsSpecialCaseVOSupression(bool bSupressVO); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.WantsSpecialCaseVOSupression // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterSluka(struct AActor* Sluka); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterSluka // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetTutorialHungerPing(bool Result); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetTutorialHungerPing // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:DynamicObjectiveCloaked(); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:DynamicObjectiveCloaked // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void FakeFeedMessage(struct FString Str, int32_t int); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.FakeFeedMessage // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetCurrentStormCategory(int32_t StormCAT); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetCurrentStormCategory // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void IsWithinStormCircleX(struct AActor* Actor, float RadiusScalar, int32_t CategoryX, bool IsInCircle); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.IsWithinStormCircleX // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void ReportStormCircleData(struct TArray<struct FVector> Circles); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.ReportStormCircleData // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:DynamicObjectiveExhausted(); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:DynamicObjectiveExhausted // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:BasicObjectiveExhausted(); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:BasicObjectiveExhausted // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetIsCheatActive_BPI(enum class ES_GameModeCheats Cheat, bool CheatIsActive); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetIsCheatActive_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetIsTutorialMode(bool IsTutorial, bool IsGBM); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetIsTutorialMode // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetTutorialMedkitPing(bool YesPing); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetTutorialMedkitPing // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetTutorialWeaponPing(bool YesPing); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetTutorialWeaponPing // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetTutorialHearthPing(bool YesPing); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetTutorialHearthPing // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Module:Dropshipalooza_BPI(bool DropshipaloozaActive); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Module:Dropshipalooza_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetIsFatAlbert_BPI(struct AActor* PlayerActor, bool IsFatAlbert); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetIsFatAlbert_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetIsHoldingTheMostData_BPI(struct AActor* Actor, bool IsFatAlbert); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetIsHoldingTheMostData_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterStrategicBush(struct AActor* Boosh); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterStrategicBush // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetDropshipSpawnerLocations_BPI(struct TArray<struct FVector> Locs); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetDropshipSpawnerLocations_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void SupplyDropAnnounce_BPI(); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.SupplyDropAnnounce_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void TeamLevelup_BPI(int32_t TeamIndex, int32_t NewLevel); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.TeamLevelup_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Rule:CanEnableAutoPing(enum class ES_KeeperInteractables KI_Type, enum class ES_ShardSizes StockpileSize, bool YouMay); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Rule:CanEnableAutoPing // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetDelayedObjectivesStarted(bool HaveStarted); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetDelayedObjectivesStarted // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void KillTeam_BPI(int32_t TeamNumber, struct AS_PlayerCharacter* lastPlayer, struct AS_PlayerController* LastPlayerCon); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.KillTeam_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetIsPlayerOnLeadingTeam_BPI(struct AActor* Player, bool IsOnLeadingTeam); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetIsPlayerOnLeadingTeam_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterGrowth(struct AActor* Actor); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterGrowth // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterSpaceJunk(struct AActor* Actor); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterSpaceJunk // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterDataUplink(struct AActor* DataUplink); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterDataUplink // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetBankCooldown_BPI(float Cooldown); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetBankCooldown_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetScoringTokenDef_BPI(struct US_ItemData* ScoringTokenDef); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetScoringTokenDef_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void UpdateTeamScores_BPI(); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.UpdateTeamScores_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetBankingMultiplier_BPI(float Multiplier); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetBankingMultiplier_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetBankingInterval_BPI(int32_t Bandwidth, float Interval); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetBankingInterval_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterGrowthSpawner(struct AActor* Growth); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterGrowthSpawner // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterSpaceJunkSpawner(struct AActor* SpaceJunk); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterSpaceJunkSpawner // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RemoveFromAllArraysAndDestroy_BPI(struct AActor* Actor); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RemoveFromAllArraysAndDestroy_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterShardAltar(struct AActor* ShardAltar); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterShardAltar // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterExemptStrategicChest(struct AActor* StrategicChest); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterExemptStrategicChest // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterShard(struct AActor* Shard); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterShard // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetSupplyDropLootTable_BPI(struct UDataTable* LootTable); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetSupplyDropLootTable_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterBasicChest(struct AActor* Chest); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterBasicChest // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterStrategicChest(struct AActor* Chest); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterStrategicChest // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetLootTable_BPI(enum class EN_LootCategory Category, struct UDataTable* LootTable); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetLootTable_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetSessionEconomy_BPI(struct UBP_SessionEconomy_C* NewParam); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetSessionEconomy_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetIsPlayerOnTeamHoldingMost_BPI(struct AActor* Player, bool IsOnLeadingTeam); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetIsPlayerOnTeamHoldingMost_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void HatchOpenFailed_BPI(); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.HatchOpenFailed_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetAnnouncerInterface_BPI(struct TScriptInterface<None> NewParam); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetAnnouncerInterface_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceIncapacitatedTeammate_BPI(int32_t TeamIndex, struct APawn* Chump, bool Cocooned); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.AnnounceIncapacitatedTeammate_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetTeamSampleCount_BPI(int32_t TeamIndex, int32_t Count); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetTeamSampleCount_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void HatchOpened_BPI(); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.HatchOpened_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void HatchOpeningAttempt_BPI(); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.HatchOpeningAttempt_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetCocoonClass_BPI(struct AActor* NewParam); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetCocoonClass_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetDropshipTransform_BPI(struct FTransform ShipSpawnLoc, struct FTransform TargetTransform); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetDropshipTransform_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetDropshipDescentDuration_BPI(float Duration); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetDropshipDescentDuration_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetLeadingTeamIndex(int32_t TeamIndex); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetLeadingTeamIndex // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetNextLoadoutUpgradeTimestamp_BPI(float Timestamp); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetNextLoadoutUpgradeTimestamp_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetPowerRank_BPI(int32_t PowerRank); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetPowerRank_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void Music_BPI(bool NotInEditor, int32_t Team, enum class ES_MusicCue Track, float Duration); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.Music_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void StopMusicOnTeam_BPI(enum class ES_MusicCue Track, int32_t Team); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.StopMusicOnTeam_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void StartMusicOnTeam_BPI(enum class ES_MusicCue Track, int32_t Team); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.StartMusicOnTeam_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void StopMusic_BPI(enum class ES_MusicCue Track); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.StopMusic_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void StartMusic_BPI(enum class ES_MusicCue Track); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.StartMusic_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetGameAnnouncementManager(); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetGameAnnouncementManager // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetTime_BPI(float CurrentTime); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetTime_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetMatchPhase_BPI(enum class EMatchPhase NewParam); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetMatchPhase_BPI // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void PlayerEvac_BPI(struct AS_PlayerController* SPlayerController, struct AActor* OptionalDropshipRef); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.PlayerEvac_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterRASP(struct AActor* RASP); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterRASP // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterRASPSpawner(struct AActor* RASPSpawner); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterRASPSpawner // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void SpectatorCam(struct APlayerController* PlayerController); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.SpectatorCam // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetGamePieceManager(struct UActorComponent* GamePieceManager); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetGamePieceManager // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AddListenerToInit(struct TScriptInterface<None> Listener); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.AddListenerToInit // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterOverlord(struct AS_AIOverlordActor* NewParam, bool BossPatrol); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterOverlord // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterRegion(struct AS_RegionVolume* RegionVolume); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterRegion // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetAllPlayerStates(struct TArray<struct APlayerState*> PlayerStates); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetAllPlayerStates // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetAllPlayerControllers(struct TArray<struct AS_PlayerController*> S_PlayerControllers); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetAllPlayerControllers // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetAllPlayerCharacters(struct TArray<struct AS_PlayerCharacter*> S_PlayerCharacters); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetAllPlayerCharacters // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterPlayerController(struct AS_PlayerController* SPlayerController); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterPlayerController // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterPlayerCharacter(struct AS_PlayerCharacter* SPlayerChar); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterPlayerCharacter // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterVehicleGantry(struct AActor* VehicleGantry); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterVehicleGantry // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterShardChest(struct AActor* Chest); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterShardChest // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterDropship(struct AActor* Dropship); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterDropship // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetNumberOfTeams(int32_t NumTeams); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetNumberOfTeams // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetNumberOfPlayers(bool DownedCountsAsLiving, int32_t NumLivingPlayers); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetNumberOfPlayers // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterRezLoc(struct AActor* RezLocSpawner); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterRezLoc // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterSalvage(struct AActor* SalvageLoc); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterSalvage // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterSupplyPodSpawner(struct AActor* SupplyDropSpawner); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterSupplyPodSpawner // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GPM:RegisterDropshipSpawner(struct AActor* DropshipSpawner); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GPM:RegisterDropshipSpawner // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetStormHazardFrequency(float Seconds); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetStormHazardFrequency // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetStormHazardDamage(float Damage); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetStormHazardDamage // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetTimeUntilStormUpgrade(float Seconds); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetTimeUntilStormUpgrade // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetSacData(struct UBP_ScourgeSacData_C* NewParam); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetSacData // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void SwitchToDropshipSpectator_BPI(struct APlayerController* PlayerController, struct AActor* BP_Dropship_PE); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.SwitchToDropshipSpectator_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetScoringData(struct FST_GameModeTeams_ScoringData NewParam); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetScoringData // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetXPData(struct US_ExperienceData* xpData); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetXPData // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void UIMessageHarvestEvent_BPI(int32_t ShardsHarvested, struct APlayerController* PlayerCon); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.UIMessageHarvestEvent_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void ReportHarvest_BPI(int32_t TeamIndex, int32_t ShardCount); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.ReportHarvest_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void GetTuningData(struct UBP_GameModeTeams_TuningData_C* TuningData); // Function BPI_GameModeTeams.BPI_GameModeTeams_C.GetTuningData // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
};

