// BlueprintGeneratedClass BPI_Gameannouncements.BPI_Gameannouncements_C
// Size: 0x28 (Inherited: 0x28)
struct UBPI_Gameannouncements_C : UInterface {

	void AnnounceRASPCalled_BPI(int32_t Team); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceRASPCalled_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceTriangulation_BPI(struct AS_PlayerController* Player); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceTriangulation_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceWarmup_BPI(struct AS_PlayerController* sPC); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceWarmup_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceShuttleVicinity_BPI(struct AS_PlayerController* sPC); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceShuttleVicinity_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void ChirpKeeperGripeSound(int32_t TeamIndex); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.ChirpKeeperGripeSound // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void ChirpKeeperDoneSound(int32_t TeamIndex); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.ChirpKeeperDoneSound // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void ChirpKeeperStartSound(int32_t TeamIndex); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.ChirpKeeperStartSound // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void ChirpMapPingSound(int32_t TeamIndex); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.ChirpMapPingSound // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void ChirpAlertSound(int32_t TeamIndex); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.ChirpAlertSound // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceSpaceJunkComplete_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceSpaceJunkComplete_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceSpaceJunkStarted_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceSpaceJunkStarted_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceShardCompleteRNG_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceShardCompleteRNG_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceShardComplete_C_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceShardComplete_C_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceShardComplete_B_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceShardComplete_B_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceShardComplete_A_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceShardComplete_A_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceShardStarted_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceShardStarted_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceGrowthStarted_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceGrowthStarted_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceBankPoweringDown_BPI(int32_t TeamIndex); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceBankPoweringDown_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceBankOffline_BPI(int32_t TeamIndex); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceBankOffline_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceAllDataBanked_BPI(struct AS_PlayerController* Player); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceAllDataBanked_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceBankBegun_BPI(struct AS_PlayerController* Player); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceBankBegun_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceKeeperCompleteRNG_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceKeeperCompleteRNG_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceKeeperComplete_C_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceKeeperComplete_C_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceKeeperComplete_B_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceKeeperComplete_B_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceKeeperComplete_A_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceKeeperComplete_A_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceKeeperDisengaged_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceKeeperDisengaged_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceKeeperEngaging_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceKeeperEngaging_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceShuttleTouchedDown_BPI(); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceShuttleTouchedDown_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceHatchOpenGoBoard_BPI(); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceHatchOpenGoBoard_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceUnsealStarted_BPI(); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceUnsealStarted_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceShipOpen_BPI(); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceShipOpen_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceCocooned_BPI(struct AS_PlayerController* SPlayerController); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceCocooned_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceGantryComplete_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceGantryComplete_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceGantryStarted_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceGantryStarted_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnouncePlayerInRasp_BPI(struct AS_PlayerController* SPlayerController); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnouncePlayerInRasp_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceSupplyDropped_BPI(); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceSupplyDropped_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceRASPonSite_BPI(); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceRASPonSite_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceCraftingLevelUp(struct AS_PlayerController* SPlayerController, int32_t NewLevel); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceCraftingLevelUp // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceResurrection_BPI(int32_t TeamIndex); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceResurrection_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceUnlockedChest_BPI(int32_t TeamIndex); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceUnlockedChest_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceLockpickSuccess_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceLockpickSuccess_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceLockpickStarted_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceLockpickStarted_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceMeteorSuccess_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceMeteorSuccess_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceObjectiveDisengaged_BPI(int32_t TeamIndex); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceObjectiveDisengaged_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AnnounceMeteorStarted_BPI(int32_t TeamIndex, struct AS_PlayerController* Activator); // Function BPI_Gameannouncements.BPI_Gameannouncements_C.AnnounceMeteorStarted_BPI // (Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
};

