// BlueprintGeneratedClass FL_MasterLibrary.FL_MasterLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct UFL_MasterLibrary_C : UBlueprintFunctionLibrary {

	void BreakArmor_Sluka(struct AActor* Character, struct FVector Location, struct FName Bone, struct FVector Direction, bool DeadState, struct FName BoneHide, struct UParticleSystem* FX, struct FName FX Bone, struct UObject* __WorldContext, struct AActor* CharacterOut, struct FTransform SpawnLocation, struct AActor* DismemberedPart); // Function FL_MasterLibrary.FL_MasterLibrary_C.BreakArmor_Sluka // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void UndoDismemberment(struct AActor* Character, struct FVector Location, struct FName Bone, struct FVector Direction, bool DeadState, struct FName BoneHide, struct UObject* __WorldContext); // Function FL_MasterLibrary.FL_MasterLibrary_C.UndoDismemberment // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void BreakArmor(struct AActor* Character, struct FVector Location, struct FName Bone, struct FVector Direction, bool DeadState, struct FName BoneHide, struct UObject* __WorldContext, struct AActor* CharacterOut, struct FTransform SpawnLocation, struct AActor* DismemberedPart); // Function FL_MasterLibrary.FL_MasterLibrary_C.BreakArmor // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void  HitReaction_Start(struct AActor* Character, struct FName BoneHit, struct FVector HitLocation, struct FVector Impulse, float BlendValue, bool TerminalState, float TerminalBlend, bool IsHuman, struct UPhysicalAnimationComponent* PhysicalAnimationComponent, bool IsDead, struct UObject* __WorldContext, struct AActor* MeshComp, struct FName BoneHitOut, struct FName BoneBelowOut, struct FVector ForceOut, struct FVector LocationOut); // Function FL_MasterLibrary.FL_MasterLibrary_C. HitReaction_Start // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void  HitBlendUpdate(struct AActor* Character, struct FName BoneBlelow, struct FVector HitLocation, struct FVector Impulse, float BlendValue, bool TerminalState, float TerminalBlend, bool IsHuman, struct UPhysicalAnimationComponent* PhysicalAnimationComponent, bool IsDead, struct UObject* __WorldContext); // Function FL_MasterLibrary.FL_MasterLibrary_C. HitBlendUpdate // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void AddImpulse(struct AActor* Character, struct FVector Impulse, struct FVector Location, struct FName Bone, struct UObject* __WorldContext); // Function FL_MasterLibrary.FL_MasterLibrary_C.AddImpulse // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void HitOrientation(struct AActor* Character, struct FVector HitLocation, struct FVector ShotFromDirection, bool SetLeft, bool SetRight, bool SetFront, bool SetBack, struct UObject* __WorldContext, bool OutLeft, bool OutRight, bool OutFront, bool OutBack); // Function FL_MasterLibrary.FL_MasterLibrary_C.HitOrientation // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void OnDeath(struct AActor* Character, struct FVector Impulse, struct FVector HitLocation, struct FName BoneHit, struct UObject* __WorldContext); // Function FL_MasterLibrary.FL_MasterLibrary_C.OnDeath // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void  HitEnd(struct AActor* Character, struct FName BoneHit, struct FVector HitLocation, struct FVector Impulse, float BlendValue, struct UPhysicalAnimationComponent* PhysicalAnimationComponent, struct FName NewParam, bool Dead, struct UObject* __WorldContext); // Function FL_MasterLibrary.FL_MasterLibrary_C. HitEnd // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
	void DoDismemberment(struct AActor* Character, struct FVector Location, struct FName Bone, struct FVector Direction, bool DeadState, struct FName BoneHide, struct UObject* __WorldContext, struct AActor* CharacterOut, struct FTransform SpawnLocation, struct AActor* DismemberedPart); // Function FL_MasterLibrary.FL_MasterLibrary_C.DoDismemberment // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0xffff8008e4a10000
};

